---
metabase_version: v0.43.4
java_packages:
  - openjdk-11-jdk
use_own_database: true
metabase_host: 0.0.0.0
metabase_db: "{{ metabase_database_name }}"
metabase_db_type: postgres
metabase_db_host: "{{ groups.postgres_primary[0] }}"
metabase_db_port: 5432
metabase_db_user: "{{ metabase_database.username }}"
metabase_db_pass: "{{ metabase_database.password }}"
