---
postgres:
  locale: "en_US.UTF-8"
  database_name: "{{ database_name }}"
  pg_hba:
    - {contype: local, databases: all, users: postgres, method: peer}
    - {contype: host,  databases: all, users: all, source: all, method: md5}
    - {contype: local, databases: all, users: all, source: all, method: md5}

postgresql_data_dir: "/var/lib/postgresql/{{ postgresql_version }}/main"
postgresql_bin_path: "/usr/lib/postgresql/{{ postgresql_version }}/bin"
postgresql_config_path: "/etc/postgresql/{{ postgresql_version }}/main"

logrotate_user: "postgres"
logrotate_dir: "/var/log/postgresql"
logrotate_files: "{{ logrotate_dir }}/*.log"
logrotate_config_file: "/etc/logrotate.d/postgres"

rsync_dir: "{{ logrotate_dir }}/*.gz"
rsync_logfile: "{{ logrotate_dir }}/rsync.log"
rsync_destination_dir: "/home/{{ deploy_user }}/logs/postgres"

prometheus_postgres_dbname: "{{ postgres.database_name }}"
backups_dir: "backups/"
backups_destination_dir: "/home/{{ deploy_user }}/backups/postgres"
backups_days_to_keep: 14

