---
roles:
  - src: ansistrano.deploy
  - src: ansistrano.rollback
  - src: cloudalchemy.prometheus
  - src: cloudalchemy.alertmanager
  - src: cloudalchemy.grafana
  - src: cloudalchemy.node_exporter
  - src: https://github.com/DavidWittman/ansible-redis.git
    version: master
    name: davidwittman.redis
  - src: ome.prometheus_postgres
  - src: http://github.com/idealista/prometheus_redis_exporter_role.git
    scm: git
    version: 2.1.0
    name: prometheus_redis_exporter
  - src: bdellegrazie.haproxy_exporter
  - src: bdellegrazie.nginx_exporter
  - src: datadog.datadog
    version: 4.15.0
  - src: libre_ops.metabase
  - src: geerlingguy.java

collections:
  - jonellis.sudoers
