# -*- mode: ruby -*-
# vi: set ft=ruby :

box = "ubuntu/focal64"

Vagrant.configure("2") do |config|
  ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    adduser ubuntu
    echo #{ssh_pub_key} >> /home/ubuntu/.ssh/authorized_keys
    echo "ubuntu ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
  SHELL

  config.vm.define 'node-01' do |node|
    node.vm.box = box
    node.vm.network "private_network", ip: "10.10.10.113"
    node.vm.hostname = "node-01"

    node.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end

    node.vm.provision "shell", inline: <<-SHELL
      # Custom provisioning script for node-01 goes here
    SHELL
  end

  config.vm.define 'node-02' do |node|
    node.vm.box = box
    node.vm.network "private_network", ip: "10.10.10.114"
    node.vm.hostname = "node-02"

    node.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end

    node.vm.provision "shell", inline: <<-SHELL
      # Custom provisioning script for node-02 goes here
    SHELL
  end
end
