---
haproxy_version: "1.6.*"
haproxy_socket: /var/lib/haproxy/stats
haproxy_chroot: /var/lib/haproxy
haproxy_user: haproxy
haproxy_group: haproxy

# Frontend settings.
haproxy_frontend_name: 'hafrontend'
haproxy_frontend_bind_address: '*'
haproxy_frontend_http_port: 80
haproxy_frontend_https_port: 443
haproxy_frontend_mode: 'http'
haproxy_cert_names:
  - /etc/ssl/simple.moh.gov.et
  - /etc/ssl/simple-demo.moh.gov.et
  - /etc/ssl/et.simple.org
haproxy_crt_list: '/etc/ssl/crt-list.txt'

# Backend settings.
haproxy_backend_mode: 'http'
haproxy_backend_balance_method: 'roundrobin'
haproxy_backend_httpchk: 'HEAD / HTTP/1.1\r\nHost:localhost'

# Extra global vars (see README for example usage).
haproxy_global_vars: []

haproxy_stats_enable: true
haproxy_stats_port: 8282
haproxy_stats_refresh: 10s
haproxy_stats_username: admin
haproxy_stats_password: "{{ monitoring_dashboard_password }}"
haproxy_stats_uri: /

haproxy_exporter_options:
  - "--haproxy.scrape-uri=https://{{ haproxy_stats_username }}:{{ haproxy_stats_password }}@localhost:{{ haproxy_stats_port }}?stats;csv"
  - "--no-haproxy.ssl-verify"
