---
- name: setup node exporter for all nodes
  hosts: all
  roles:
    - monitoring
    - cloudalchemy.node_exporter

- name: setup postgres exporter
  hosts: postgres
  roles:
    - monitoring
    - ome.prometheus_postgres

- name: setup redis exporter
  hosts: redis
  roles:
    - monitoring
    - prometheus_redis_exporter
  become: true

- name: setup HAProxy exporter
  hosts: load_balancing
  roles:
    - monitoring
    - bdellegrazie.haproxy_exporter

- name: setup nginx exporter
  hosts: webservers
  roles:
    - monitoring
    - bdellegrazie.nginx_exporter

- name: setup Prometheus and Alertmanager
  hosts: prometheus
  vars_files:
    - "roles/simple-server/vars/{{ deploy_env }}/secrets.yml"
  roles:
    - monitoring
    - cloudalchemy.prometheus
    - cloudalchemy.alertmanager

- name: setup Grafana
  hosts: grafana
  roles:
    - monitoring
    - cloudalchemy.grafana
