---
# nginx + passenger tasks
- name: install PGP key supprt
  apt: pkg={{ item }} state=latest
  become: true
  with_items:
    - dirmngr
    - gnupg

- name: add passenger PGP key
  apt_key: keyserver=keyserver.ubuntu.com id=561F9B9CAC40B2F7 state=present
  become: true

- name: add passenger apt repo
  apt_repository: repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ ansible_distribution_release }} main' state=present
  become: true
  register: passenger_repo

- name: apt-get update
  apt:
    update_cache: yes
  become: true
  when: passenger_repo.changed

- name: install passenger dependencies
  apt: pkg={{ item }} state=latest
  become: true
  with_items:
    - apt-transport-https
    - ca-certificates
    - nginx-extras

- name: install nginx and passenger for Ubuntu 20.04
  apt: pkg={{ item }} state=latest
  become: true
  with_items:
    - nginx
    - libnginx-mod-http-passenger
  when: ansible_distribution_version == "20.04"

- name: install passenger module for Ubuntu 16.04 # This should be removed when we stop supporting Ubuntu 16.04
  apt: pkg=passenger state=latest
  become: true
  when: ansible_distribution_version == "16.04"

- name: re-configure nginx
  template: src=etc/nginx/nginx.conf dest=/etc/nginx/nginx.conf
  become: true

- name: set passenger module config
  copy: src=etc/nginx/conf.d/mod-http-passenger.conf dest=/etc/nginx/conf.d/mod-http-passenger.conf
  become: true
  notify: restart nginx

- name: disable the default nginx config
  file: path={{ item }} state=absent
  become: true
  with_items:
    - /etc/nginx/sites-enabled/default
  notify: restart nginx

- name: get installed site configs
  shell: ls -1 /etc/nginx/sites-available
  register: sites_available_contents

- name: get enabled site configs
  shell: ls -1 /etc/nginx/sites-enabled
  register: sites_enabled_contents

- name: add site configs
  template:
    src: etc/nginx/sites-available/simple.org
    dest: /etc/nginx/sites-available/{{ domain_name }}
  become: true
  notify: restart nginx

- name: enable site configs
  file:
    state: link
    src: /etc/nginx/sites-available/{{ domain_name }}
    dest: /etc/nginx/sites-enabled/{{ domain_name }}
  become: true

- name: restart nginx
  become: true
  command: /bin/true
  notify: restart nginx
  tags: restart-passenger

- name: enable monit for nginx
  file: >
    state=link
    src=/etc/monit/conf-available/nginx
    dest=/etc/monit/conf-enabled/nginx
  become: true
  notify: restart monit
