version: v1.0
name: Update Ethiopia Demo config
blocks:
  - name: Ansible update
    task:
      jobs:
        - name: Update config
          commands:
            - checkout
            - make init
            - make update-app-config hosts=ethiopia_demo
            - make update-ssh-keys hosts=ethiopia_demo
      secrets:
        - name: ansible-vault-passwords
        - name: semaphore-deploy-key
      prologue:
        commands:
          - chmod 600 ~/.ssh/semaphore_id_rsa
          - ssh-add ~/.ssh/semaphore_id_rsa
agent:
  machine:
    type: e2-standard-2
    os_image: ubuntu2204
